apiVersion: v1
kind: Pod
metadata:
  name: psql-test
  namespace: edu-azad-salimof
spec:
  restartPolicy: Never
  containers:
    - name: psql
      image: postgres:16
      command: ["sleep", "3600"]
      env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: postgres
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: postgres
              key: port
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres
              key: name
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: PGSSLMODE
          value: verify-full
        - name: PGSSLROOTCERT
          value: /root/.postgresql/root.crt
      volumeMounts:
        - name: pg-root-crt
          mountPath: /root/.postgresql
          readOnly: true
  volumes:
    - name: pg-root-crt
      secret:
        secretName: pg-root-crt
        defaultMode: 0600